### ISSUE TITLE
Templates with .yml extension don't support Handlebars

### ISSUE THREAD

**Issue by mfonsen** [takomo-io/takomo#126]
Templates with `.yml` extension don't support Handlebars. This is inconsistent as stack configs with `.yml` extension do support Handebars.

It's possible to use a subset of Handlebars in templates so that the files are valid Yaml. If you do this then editors and linters work in a sensible way without manual configuration.

Takomo version 2.11.1

**Comment by hmeltaus** [comment]
It was a deliberate decision to use `.hbs` file extensions to mark templates that should be processed with Handlebars. The idea was to prevent unwanted processing, and also to allow use of additional templating engines in future, each with their own file extensions.

I understand your point of view on this and will consider changing the logic with templating and file extensions. Anyway, it would be a breaking change and require a new major version release.

**Comment by hmeltaus** [comment]
Now that I've thought this a bit more, I think that enabling Handlebars by default for all `.yml` and `.json` stack template files would be a good decision. I didn't come up any good reasons why not to do that. It doesn't really affect performance and shouldn't break any valid yaml or json template.

I'm planning to release a major version with some API changes, and this change could be included in that.

In the meantime, we could use `.hbs.yml` file extension to mark template files to be processed with Handlebars. That would be a backwards compatible solution and easily doable.

**Comment by mfonsen** [comment]
The `hbs.yml` extension would solve at least this issue without introducing any potentially confusing side effects.

Maybe later one could explicitly define the processor as part of the template definition in stack config. Maybe this could enable built-in or custom integration to AWS CDK or other similar options.

**Comment by hmeltaus** [comment]
Let's enable Handlebars processing for all stack template files with `.yml` and `.json` file extensions. After this change, the`.hbs` file extension is no longer needed and will be marked as deprecated, and will be removed in the next major release after 3.0.0.

**Comment by hmeltaus** [comment]
Included in release 3.0.0
