### ISSUE TITLE
An error occurs when reviewing removed stack parameters 

### ISSUE THREAD

**Issue by hmeltaus** [takomo-io/takomo#170]
An error occurs when reviewing changes to stack parameters if the following conditions are met:

- at least two parameters have changed
- at least one parameter is removed

The error affects only to reviewing of changes but will exit the command before actual deployment process can begin.

**Comment by mfonsen** [comment]
Thank you! I verified that the problem I had with 3.4.0 (`Unsupported parameter operation: 'delete'`) is now gone with 3.4.1.
