### ISSUE TITLE
Tags cannot be used as stack configuration parameters

### ISSUE THREAD

**Issue by stenla-ws** [takomo-io/takomo#29]
According to https://takomo.io/guide/stacks/variables-and-templating.html#variables-in-stack-configuration-files , tags _might_ be used as parameters in stack configuration files.

config.yml
<pre>
project: web
regions: 
    - eu-north-1
tags:
    Environment: dev
</pre>

vpc.yaml
<pre>
template: infra/vpc.yml
parameters:
    CidrBlock: 192.168.1.0/18
    Project: {{ stackGroup.project }}
    Environment: {{ stackGroup.tags.Environment }}
</pre>

Using this I end up getting a following error when running <code>tkm stacks list deploy</code>
<pre>
ERROR
-----
An error occurred while rendering template: "Environment" not defined in [object Map] - 5:20

File:        /my_path/takomo/stacks/dev/infra/vpc.yml
Line number: 5
Column:      20
</pre>

This works when I create additional entry into config.yml
<pre>
project: web
regions: 
    - eu-north-1
tags:
    Environment: dev
data:
    Environment: dev
</pre>

And use this with vpc.yml
<pre>
template: infra/vpc.yml
parameters:
    CidrBlock: 192.168.1.0/18
    Project: {{ stackGroup.project }}
    Environment: {{ stackGroup.data.Environment }}
</pre>

**Comment by hmeltaus** [comment]
This is duplicate to #27
