### ISSUE TITLE
Option to initialise a new project

### ISSUE THREAD

**Issue by stenla-ws** [takomo-io/takomo#30]
Takomo should have an option to init a new project:

- Request project name
- Request region(s) where stacks will be launched
- Create correct directory structure
- Create base config.yml

Optional: create also vpc stacks used on _quick-start_ so that testing Takomo would be as easy as possible.

<pre>
tkm init
Please enter your project name: web
Please enter your region(s), separated with comma: eu-north-1
Creating directories...
... stacks
... templates
Creating base configuration...
... stacks/config.yml
</pre>

This could also work from command line: tkm init --projectname web --regions eu-north1

**Comment by hmeltaus** [comment]
Done and included in takomo 1.3.0
