### ISSUE TITLE
Inconsistency on confirmation prompts

### ISSUE THREAD

**Issue by stenla-ws** [takomo-io/takomo#31]
<pre>
Following 1 stack(s) will be deployed:

  + /vpc.yml/eu-west-1:
      name:          vpc
      status:        PENDING

? Continue to deploy the stacks? Yes
2020-05-18 09:12:09 +0300 [info ] - /vpc.yml/eu-west-1 - Create stack

Changes to stack: /vpc.yml/eu-west-1

  + VPC
      type:                      AWS::EC2::VPC
      physical id:               undefined
      replacement:               undefined
      scope:                     
      details:

Add: 1, Modify: 0, Remove: 0

? Deploy stack? yes
</pre>

- First prompt uses pressing Yes/no (key entry) or enter.
- Second prompt uses arrow keys or enter.
- It would be more clear for the user if input method would be similar on both.

**Comment by hmeltaus** [comment]
There's a plan to add new options to this and other prompts for better user experience.

For example, the first prompt "Continue to deploy the stacks?" could also have an option to continue deployment and answer "yes" to all remaining prompts. Also, the next prompt that confirms changes to a stack could have similar option that skip all remaining prompts.

We'll link this issue to the one describing this new feature once it's ready for development.
