### ISSUE TITLE
external-stack-output hitting CloudFormation API rate limit

### ISSUE THREAD

**Issue by otto-liljalaakso-nt** [takomo-io/takomo#458]
We have a monorepo application with monolithic deployment that has been in development for more than five years. Currently the team has eight developers. For each pull request, we deploy a (more or less) full instance of our application for testing. All pull requests share a common dev AWS account. This means quite heavy usage of the CloudFormation API in the dev account.

Lately, we have started observing that sometimes deployment of PR environments fail due to _Error: Throttling: Rate exceeded_ from CloudFormation. In the cases whose logs I have investigated, the errors comes from `external-stack-output` resolver, which we use heavily, almost 200 times over all our stacks configs.

Looking at external-stack-output-resolver.ts, it does not do any caching, but calls CloudFormation's Describe Stacks endpoint on every invocation. In face of CloudFormtation throttling we are experiencing, that seems quite wasteful. Of those almost 200 calls, only about 50 are unique.

I propose to add caching in external-stack-outputs, so that it caches the outputs and responds to futher requests for the same stack from the cache.

**Comment by hmeltaus** [comment]
Hello, that's a good idea! Caching by default might break some deployments, so to ensure backwards compatibility, I think we need to add a new property that can be used to enable caching. In addition to caching, there should be retry to handle random network and throttling errors.

**Comment by hmeltaus** [comment]
New property `cache` added in release v7.3.0. When set to true, external stack output resolver caches resolved parameter values for the duration of the deploy operation.

This is how you use it:

```
parameters:
  ExampleParameter:
    resolver: external-stack-output
    stack: my-stack
    region: us-east-1
    output: MyOutputName
    cache: true
```

This should reduce the number of API calls.
