### ISSUE TITLE
General guidance regarding stack dependencies

### ISSUE THREAD

**Issue by nix222** [takomo-io/takomo#80]
Hi,
According to the docs, dependencies can be specified in `depends` property in the config file. Can we reference stacks other than those present in the current project? I mean if we already have a Cloudformation stack deployed, and it is not defined in the current project, and therefore it does not have a `stack path`, can it be referenced somehow as a dependency?

**Comment by hmeltaus** [comment]
`depends` is intended to specify dependencies inside the current project and can't be used for dependencies outside the project.

Stack dependencies are used to ensure that the stacks are deployed in correct order, i.e. the stacks that other stacks depend on are created/updated before of the dependent stacks.

Can you tell more about your use case?

**Comment by alexlykasov** [comment]
We are using a sort of layered setup of Cloudformation templates, each layer being managed by different people. We have a set of infrastructure-related templates such as VPC, subnets, IAM policies, and roles managed by the infrastructure team. Developers are managing the services needed to run applications: lambdas, ECS, CW, S3. And my idea is that developer stacks are dependant on infrastructure stacks in the sense that an app stack can reference for example a subnet id or a role arn defined in infra stack. In this sense, it would be nice to specify the name of infra stack as a dependency in an app stack and the output from the latter would be mapped to the application stack parameters.

But yes, this use case does not apply to the order of deployments in the current project.

**Comment by nix222** [comment]
We are using a sort of layered setup of Cloudformation templates, each layer being managed by different people. We have a set of infrastructure-related templates such as VPC, subnets, IAM policies, and roles managed by the infrastructure team. Developers are managing the services needed to run applications: lambdas, ECS, CW, S3. And my idea is that developer stacks are dependant on infrastructure stacks in the sense that an app stack can reference for example a subnet id or a role arn defined in infra stack. In this sense, it would be nice to specify the name of infra stack as a dependency in an app stack and the output from the latter would be mapped to the application stack parameters.
But yes, this use case does not apply to the order of deployments in the current project.

**Comment by hmeltaus** [comment]
You can achieve this with external stack output resolver. It reads stack outputs from stacks managed outside the current project and uses them as input parameters for stacks. You can find the related documentation here https://takomo.io/guide/stacks/parameter-resolvers.html#external-stack-output . There's also an example which should be helpful.

The documentation isn't perfect and I'm currently working to improve it. So, if you can't find answers there, don't hesitate to ask help here.

**Comment by nix222** [comment]
thanks for the clarification! it's clearer now
