### ISSUE TITLE
Lack of Windows support to be documented?

### ISSUE THREAD

**Issue by mfonsen** [takomo-io/takomo#82]
Currently `packages/takomo/package.json` seems to be the only place where supported OSs are defined.

Should the documentation clearly indicate this if this is a design decision? Specifically that Windows is not supported?

Heard this from a Windows user who luckily has WSL available. Many similar deployment tools are cross platform.

**Comment by hmeltaus** [comment]
Lack of Windows support is also mentioned in getting started guide but should be stated more clearly. 

Not supporting Windows was a deliberate choice that allowed me to focus more on implementing features.

I know that Takomo should support Windows. I'm also pretty sure that adding the support is possible and might not even require a huge effort, but for now, it needs to wait as there are other more important tasks to do.

**Comment by hmeltaus** [comment]
Documentation now includes a big warning about Windows support. Created an issue to add WIndows support #88
