### ISSUE TITLE
How to use iamRoleArns for custom resolvers?

### ISSUE THREAD

**Issue by mfonsen** [takomo-io/takomo#83]
Documentation for [parameter resolvers](https://takomo.io/docs/stacks/parameter-resolvers) mentions `iamRoleArns`. But there isn't an example code that uses other roles. How does it work?

Using a resolver I would like to upload a lambda functions code to s3 and then return the s3 path.

**Comment by hmeltaus** [comment]
That requires diving deeper into Takomo internals and is something I need to document better. You can see how the built-in resolvers are implemented and are using credentials and roles. External stack output resolver is a good place to start from https://github.com/takomo-io/takomo/blob/master/packages/stacks-resolvers/src/impl/external-stack-output-resolver.ts . I will improve the related documentation soon.

**Comment by hmeltaus** [comment]
There's now an example demonstrating how to use IAM roles with custom resolvers https://github.com/takomo-io/takomo-examples/tree/master/custom-resolvers/iam-roles

I'll add this to docs as well along with more instructions and explaining.

**Comment by hmeltaus** [comment]
The bare bones example of a custom resolver with IAM role arn is now added to docs https://takomo.io/docs/examples/custom-resolver-with-iam-role
